config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'

   resources :static_pages
 
   resources :lists

   resources :movies
  
   resources :activitys
  
   resources :shop_lists


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates_presence_of :name, :description, :link
end

app/models/movie.rb
class Movie < ApplicationRecord
    
end

app/models/shop_list.rb
class ShopList < ApplicationRecord
    
end

app/controllers/activitys_controller.rb
class ActivitysController < ApplicationController
  
  def index
    @activitys = Activity.all

  end

  def new
   @activitys = Activity.new

  end

  def create
    @activitys = Activity.new(activitys_params)
    if @activitys.save
      redirect_to @activitys
    else
      render json: { errors: Activity.errors }, status: :unprocessable_entity 
    end
  end

  def show
    @activitys = Activity.find(activitys_params[:id])
     render json: activitys([:id])
     
  end

  def delete
     @activitys = Activity.destroy(activitys_params[:id])

  end

  private
     
     def activitys_params
      params.require(:activitys).permit(:name, :description, :funlevel, :complete )
     end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
 
  def index
    @lists = List.all
  end

  def new
    @lists = List.new
    render partial: "form"
  end


  def create
    @lists = List.new(list_params)
    if @lists.save
      redirect_to @lists
    else
      render json: { errors: List.errors }, status: :unprocessable_entity 
    end
  end

  def show
  end

  def update
    @lists = List.find(params[:id])
    lists.update(name: !List.name)
    render json: @lists  
  end

  def destroy
    @lists = List.find(params[:id]).destroy
    render json: { message: 'List deleted' }
  
  end

  private

  def list_params
    params.require(:list).permit(:name, :link, :description )
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # before_action
  
  def index
    @movies = Movie.all  
  end

  def new
   @movies = Movie.new
  end

  def create
    @movies = Movie.create(movies_params[:id])
     if @movies.save
       render json: @movies
      else
      render json: {errors: Movie.errors }, status: :unprocessable_entity
    end
  end

  def show
    @movies = Movie.find(movies_params[:id])
     respond_to do |format|
     format.html #show.html.erb
     format.json { render json: @movies }
     end
  end

  def update
    @movies = Movie.update(movies_params[:id])
      if movies.save
      render json: movies.all 
    else
     redirect_to 
    end
  end

  private

  def movies_params
   params.require(:movie).permit(:title, :description, :link, :watched, :rating )
  end

end

app/controllers/shop_lists_controller.rb
class ShopListsController < ApplicationController
  
  def index
   @shoplists = ShopList.all
  end

  def new
    @shoplists = ShopList.new
  end

  def create
    @shoplists = ShopList.new(shop_params)
    if @shoplists.save
      redirect_to shop_list_path(@shoplists)
    else
      render json: {errors: ShopList.errors }, status: :unprocessable_entity
    end
  end

  def update

  end

  def show
   @shoplists = ShopList.find(params[:id])
   render json: @shoplists

  end
  
  private

  def shop_params
    params.require(:shop_lists).permit(:item, :gift, :link)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def about
    
  end

  def home
    
  end

end

app/helpers/activitys_helper.rb
module ActivitysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/shop_lists_helper.rb
module ShopListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activitys/index.html.erb
<div >
  <h1>My Chore List</h1>
    <% @activitys.each do |activitys|   %>  
  <table class="block" >
    <tr>
      <th> Name </th>
      <th> Description </th>
      <th> Fun Level </th>
      <th> Complete </th>
    </tr>
   <tr>
      <td <%= @activitys.name %> </td>
      <td <%= @activitys.description %> </td>
      <td <%= @activitys.funlevel %> </td>
      <td <%= @activitys.complete %> </td> 
      <td <%= link_to "Change Complete", edit_activity_path(activity) %> </td>
    </tr>
     <% end %>

       <%  if @activitys.size == 0  %>    
        <em> I'm sorry Im lazy. Care to add something to my list? </em>
       <% end %>

   </table>  
</div >
<div >
  <span> <%= link_to "Add Chore to List", new_activity_path %> </span>
</div>

app/views/activitys/new.html.erb
  <div class="row">
    <h1>Add a Chore </h1>
    <div class="col-xs-12 col-md-8" >
       <%= form_for @activitys do |f| %> 
         <%= f.label "Name" %>  
         <%= f.text_field :name, :required => true %>
         <br />
         <%= f.label "Description" %>  
         <%= f.text_area :description %>
           <br />
         <%= f.label "Item Link" %>
         <%= f.text_field :link %> 
          <br /> 
         <%= f.submit "Create", class: 'ui button primary' %> 
     <% end %>

     
  </div>

app/views/activitys/show.html.erb
<h1>Activitys#show</h1>

<p>Find me in app/views/activitys/show.html.erb</p>

app/views/layouts/_dropDown.html.erb
<div class="ui teal buttons">
  <div class="ui button"> Lists </div>
  <div class="ui floating dropdown icon button">
    <i class="dropdown icon"> </i>
    <div class="menu">
       <div class="item" data-value="scale"> Quotes </div>
       <div class="item" data-value="scale"> Shopping </div>
       <div class="item" data-value="scale"> Chores </div>
       <div class="item" data-value="scale"> Movies </div>
    </div>
  </div>
</div>

app/views/layouts/_navBar.html.erb
<ul>
<li><a href="static_pages#home">Home</a></li>
<li><a href="static_pages#news">News</a></li>
<li class="dropdown">
  <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
  <div class="dropdown-content">
    <a href="#">Link 1</a>
    <a href="#">Link 2</a>
    <a href="#">Link 3</a>
  </div>
</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Multi List | Rails only </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
   <header class="container">
    <nav class="navbar navbar-default">
    <div class="container-fluid">
       <div class="navbar-header">
        <h1> Charlie Jergins </h1>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>  <%= link_to 'Home', root_path %>  </li>
          <li> <%= link_to 'Chores', activitys_path %></li>
          <li> <%= link_to 'Shopping', shop_lists_path%> </li>
          <li> <%= link_to 'Quotes', root_path%> </li>
          <li> <%= link_to 'Movies', movies_path %></li>

        </ul>
       </div>
     </nav>
    </header>
   <div class="container">
        <%= yield %>
    </div> 
    <h3> Built with Coffee </h3>
  </body>
</html>

app/views/lists/_form.html.erb
   <% if list.errors.any? %>
  <div id="notice" class="error">
     
  </div>
  
  <h1> Create A New List: </h1>
  <div class="ui_form" >
      <%= form_for @lists do |f| %> 
     <div class="feild"> 
        <%= f.label "List Name"  %>  
        <br />
        <%= f.text_field :name, :required => true, autofocus: true %>
     </div>
     <div class="feild">
        <%= f.label "Description"  %>  
        <br />  
        <%= f.text_area :description, :required => true %>
     </div> 
     <div class="feild"> 
        <%= f.label "List Link"  %>
          <br />  
        <%= f.text_field :link, :required => true %> 
     </div>
        <%= f.submit "Create", class: 'ui button primary' %> 
     <% end %>
  </div>

app/views/lists/index.html.erb
<section class="hero-area">
  <div>
     <div >
      <h1 class="ui header"> Lists to Choose from: </h1>  
         <% @lists.each do |l| %>
         <ul id="listUL" class="list">
              <li> <%= l.name %> : <%=  l.description %> 
                        <br />  
                   <%= link_to l.link, l.link %> 
              </li>
         </ul>   
        <% end %>

	 </div>
	<div class="block">
		<a data-scroll href="#lists_show" class="btn btn-transparent">See Lists</a>
		<span> or </span>
		<%= link_to 'Create New List', new_list_path  %>
	</div>
  </div>
</section>

app/views/lists/show.html.erb
<h1> Lists to Choose from: </h1>
  
<p id="notice" class=<%= notice ? 'success' : ''%>> <%= notice %> </p>

  <% @list.each do |list| %>
  <ul>
      <li> <%= list.name %> 
            <%= link_to 'Delete List', list_path, are you sure?  %>
      </li>
  </ul>   
  <% end %>   
  <span> <%= link_to 'Go To List', list_path:id %> </span>
  

app/views/movies/index.html.erb
<div>

<h1 class="center aligned">Movie Watch List</h1>

<table id="movietable" class="ui striped right aligned table" >
 <thead>
  <tr >
    <th> Title </th>
    <th> Description </th>
    <th> Link </th>
    <th> Watched </th>
    <th> Rating </th>
  </tr>
 </thead>
  
 <tbody>
    <%  @movies.each do |m| %>
  <tr  >  
     <td> <%= m.title %> </td>
     <td> <%= m.description %> </td>
     <td> <%= m.link %> </td>
     <td> <%= m.watched %> </td> 
     <td> <%= m.rating %> </td>
  </tr>   
  <% end %>
  <%  if @movies.length == 0 %> 
  <em> Im sorry No Movies to Display </em>
  <% end %>
  </tbody>
  </table>  
</div>
<div>
  <span> <%= link_to "Add Movie to List", new_movie_path %> </span>
  <span> <%= link_to "Go Back to Lists", lists_path %> </span>
</div>

app/views/movies/new.html.erb
<div class="row">
  <h1>Movies To Watch </h1>
  <div class="col-xs-12 col-md-8" >
		  <%= form_for @movies do |f| %> 
         <%= f.label "Movie Title" %>  
           <%= f.text_field :title, :required => true, autofocus: true %>
           <br />
         <%= f.label "Description" %>  
           <%= f.text_area :description, :required => true %>
           <br />
         <%= f.label "Link to Page" %>
           <%= f.text_field :link, :required => true %> 
           <br /> 
          <%= f.label "Have you seen the movie?" %>
           <%= f.text_field :watched, :required => true %>
           <br />
         <%= f.label "Stars" %>
           <%= f.text_field :rating %>
         <%= f.submit "Create" %> 
         <% end %>
	 </div>
</div>

app/views/movies/show.html.erb
<h1> Movies </h1> 
 
 <%= @movies.for_each do |movies| %> </h3>
    <div >
      <h1> Lists to Choose from: </h1>  
         
         <ul>
              <li> <%= movie.title %> </li>
         </ul>   
        <% end %>
<%= end %>

app/views/shop_lists/index.html.erb
<div >
  <h1>Shoping List</h1>
  <%  @shoplists.each do |shoplist| %>
<table class="shoptable" >
  <tr>
    <th> Item </th>
    <th> Gift </th>
    <th> Link </th>
  </tr>
    
  <tr>
     <td <%= shoplist.item %> </td>
     <td <%= shoplist.gift %> </td>
    <td <%= shoplist.link %> </td>
   </tr>
   <% end %>

   <%  if @shoplists.size == 0  %>    
      <em> "Im sorry No Items to Display" </em>
   <% end %>

</table>
  
</div >

app/views/shop_lists/new.html.erb
<h1>ShopLists#new</h1>
<p>Find me in app/views/shop_lists/new.html.erb</p>

app/views/shop_lists/show.html.erb
<h1>ShopLists#show</h1>

<p>Find me in app/views/shop_lists/show.html.erb</p>

app/views/static_pages/about.html.erb
<h1> Day in the life of Charlie </h1>


<p> It's me, I know. Humbling. </p>

app/views/static_pages/home.html.erb
 <section class="hero-area">
	<div class="block">
		<h1> Enter The Charlie Experience </h1>
		<h4> This site made exclusivly by and for Charlie. These are my interests my hobies and chores that need doing. Great way for Charlie to stay on track! </h4>
		<div >
		  <p> <%= link_to 'See Lists', lists_path %> </p>
		  <br />
        <p> or </p>
        <br />
		  <%= link_to 'Create New List', new_list_path  %>
		</div>
	</div>
 </section>